---
to: <%= h.src() %>/<%= h.changeCase.lower(name) %>/templates/components/theme/a-button/a-button.js
---
/**
 * DO NOT EDIT THIS FILE.
 * It's generated automatically by 'yarn build' command.
 * @preserve
 **/
