---
to: <%= h.src() %>/<%= h.changeCase.lower(name) %>/templates/components/suggestions/a-input/a-input.js
---
/**
 * DO NOT EDIT THIS FILE.
 * It's generated automatically by 'yarn build' command.
 * @preserve
 **/
