---
to: <%= h.src() %>/<%= h.changeCase.lower(name) %>/templates/components/uncategorized/o-dialog/o-dialog.js
---
/**
 * DO NOT EDIT THIS FILE.
 * It's generated automatically by 'yarn build' command.
 * @preserve
 **/
